name: Required with no Default
description: Replace-With-Your-Action-Description
inputs:
  path_dockerfile:
    description: "Path to Docker File"
    required: false
    default: Dockerfile

  image_name:
    description: "Name for the DockerImage"
    required: true

  tag_name:
    description: "Tag added to the final image"
    required: false
runs:
  using: composite
  steps:
    - name: Create Docker Image
      run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
          export TAG=$(date +%s)
        else
          export TAG="${{ inputs.tag_name }}"
        fi
        docker build . --file ${{ inputs.path_dockerfile }} --tag ${{inputs.image_name}}:$TAG
        docker image ls
      shell: bash