# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  docker_image_name: 'academy'
  docker_tag_name: 'quack1'
  artifact_name: 'artifactoooooo'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Custom Action Build
        uses: ./.github/actions/maven_build

      - name: Create Docker Image
        uses: ./.github/actions/docker_build
        with:
          image_name: $docker_image_name
          tag_name: $docker_tag_name

      - name: Save image On File
        run: docker save -o "${{ env.docker_image_name }}.tar" $docker_image_name:$docker_tag_name

      - name: Upload File
        uses: actions/upload-artifact@v4
        with:
          name: $artifact_name
          path: ${{ env.docker_image_name }}.tar


  coisa_build:

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: $artifact_name

      - name: Load Docker Image
        run: docker load -i ${{ env.docker_image_name }}.tar

      - name: List Images
        run: docker image ls




